# Generated by Django 3.2 on 2023-10-14 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Картинка')),
                ('image_order', models.PositiveIntegerField(default='1', verbose_name='Порядковый номер')),
                ('event_organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.eventorganizer', verbose_name='Организатор')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
