# Generated by Django 3.2 on 2023-10-26 06:19

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('image_order',), 'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterField(
            model_name='eventorganizer',
            name='long_description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Описание'),
        ),
    ]
