# Generated by Django 3.2 on 2023-11-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_tinymce_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorganizer',
            name='short_description',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Краткое описание'),
        ),
    ]
