# Generated by Django 3.2 on 2023-11-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_textfield_to_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorganizer',
            name='latitude',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='eventorganizer',
            name='longitude',
            field=models.FloatField(verbose_name='Долгота'),
        ),
    ]
