# Generated by Django 3.2 on 2023-11-20 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_updated_positiveintegerfield'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventOrganizer',
            new_name='Place',
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='event_organizer',
            new_name='place',
        ),
    ]
